#ifndef _ISP_CTRL_API_H_
#define _ISP_CTRL_API_H_

struct ctrl_range {
	int min;
	int max;
};

#define V4L2_CID_BASE 0
#define V4L2_CID_BRIGHTNESS (V4L2_CID_BASE+0)
#define V4L2_CID_CONTRAST (V4L2_CID_BASE+1)
#define V4L2_CID_SATURATION (V4L2_CID_BASE+2)
#define V4L2_CID_HUE (V4L2_CID_BASE+3)
#define V4L2_CID_NONE (V4L2_CID_BASE+4)
#define V4L2_CID_AUDIO_VOLUME (V4L2_CID_BASE+5)
#define V4L2_CID_AUDIO_BALANCE (V4L2_CID_BASE+6)
#define V4L2_CID_AUDIO_BASS (V4L2_CID_BASE+7)
#define V4L2_CID_AUDIO_TREBLE (V4L2_CID_BASE+8)
#define V4L2_CID_AUDIO_MUTE (V4L2_CID_BASE+9)
#define V4L2_CID_AUDIO_LOUDNESS (V4L2_CID_BASE+10)
#define V4L2_CID_BLACK_LEVEL (V4L2_CID_BASE+11) /* Deprecated */
#define V4L2_CID_AUTO_WHITE_BALANCE (V4L2_CID_BASE+12)
#define V4L2_CID_DO_WHITE_BALANCE (V4L2_CID_BASE+13)
#define V4L2_CID_RED_BALANCE (V4L2_CID_BASE+14)
#define V4L2_CID_BLUE_BALANCE (V4L2_CID_BASE+15)
#define V4L2_CID_GAMMA (V4L2_CID_BASE+16)
#define V4L2_CID_EXPOSURE (V4L2_CID_BASE+17)
#define V4L2_CID_AUTOGAIN (V4L2_CID_BASE+18)
#define V4L2_CID_GAIN (V4L2_CID_BASE+19)
#define V4L2_CID_HFLIP (V4L2_CID_BASE+20)
#define V4L2_CID_VFLIP (V4L2_CID_BASE+21)
#define V4L2_CID_HCENTER (V4L2_CID_BASE+22)
#define V4L2_CID_VCENTER (V4L2_CID_BASE+23)
#define V4L2_CID_POWER_LINE_FREQUENCY (V4L2_CID_BASE+24)
#define V4L2_CID_HUE_AUTO (V4L2_CID_BASE+25)
#define V4L2_CID_WHITE_BALANCE_TEMPERATURE (V4L2_CID_BASE+26)
#define V4L2_CID_SHARPNESS (V4L2_CID_BASE+27)


#define V4L2_CID_USER_BASE 0x0000
#define RTS_V4L2_CID_BASE (V4L2_CID_USER_BASE | 0xf000)
#define RTS_V4L2_CID_GREEN_BALANCE (RTS_V4L2_CID_BASE + 0)
#define RTS_V4L2_CID_IQ_TABLE (RTS_V4L2_CID_BASE + 1)
#define RTS_V4L2_CID_DAY_NIGHT (RTS_V4L2_CID_BASE + 2)
enum rts_isp_day_night {
	RTS_ISP_DAY,
	RTS_ISP_NIGHT,
};
#define RTS_V4L2_CID_DYNAMIC_FPS (RTS_V4L2_CID_BASE + 3)
#define RTS_V4L2_CID_DYNAMIC_IQ (RTS_V4L2_CID_BASE + 4)
#define RTS_V4L2_CID_TEMPORAL_DENOISE (RTS_V4L2_CID_BASE + 5)
#define RTS_V4L2_CID_DEHAZE (RTS_V4L2_CID_BASE + 6)
#define RTS_V4L2_CID_DEHAZE_LEVEL (RTS_V4L2_CID_BASE + 7)
#define RTS_V4L2_CID_LDC (RTS_V4L2_CID_BASE + 8)
#define RTS_V4L2_CID_GRAY (RTS_V4L2_CID_BASE + 9)
#define RTS_V4L2_CID_AUTO_CCM (RTS_V4L2_CID_BASE + 10)
#define RTS_V4L2_CID_CCM_MATRIX (RTS_V4L2_CID_BASE + 11)
#define RTS_V4L2_CID_WDR_MODE (RTS_V4L2_CID_BASE + 12)
enum rts_isp_wdr_mode {
	RTS_ISP_WDR_INNER_DISABLE,
	RTS_ISP_WDR_INNER_MANUAL,
	RTS_ISP_WDR_INNER_AUTO,
};
#define RTS_V4L2_CID_WDR_LEVEL (RTS_V4L2_CID_BASE + 13)
#define RTS_V4L2_CID_AUTO_GAMMA (RTS_V4L2_CID_BASE + 14)
#define RTS_V4L2_CID_GAMMA_CURVE (RTS_V4L2_CID_BASE + 15)
#define RTS_V4L2_CID_AUTO_YGAMMA (RTS_V4L2_CID_BASE + 16)
#define RTS_V4L2_CID_YGAMMA_CURVE (RTS_V4L2_CID_BASE + 17)
#define RTS_V4L2_CID_OUTPUT_POSITION (RTS_V4L2_CID_BASE + 18)
#define RTS_V4L2_CID_COLOR_RANGE (RTS_V4L2_CID_BASE + 19)
enum rts_isp_color_range {
	RTS_ISP_COLOR_RANGE_BT601_STUDIO_SWING,
	RTS_ISP_COLOR_RANGE_BT601_FULL_SWING,
	RTS_ISP_COLOR_RANGE_BT709_STUDIO_SWING,
	RTS_ISP_COLOR_RANGE_BT709_FULL_SWING,
};
#define RTS_V4L2_CID_NR_LEVEL (RTS_V4L2_CID_BASE + 20)
#define RTS_V4L2_CID_DE_LEVEL (RTS_V4L2_CID_BASE + 21)
#define RTS_V4L2_CID_SNR_CROP_X (RTS_V4L2_CID_BASE + 22)
#define RTS_V4L2_CID_SNR_CROP_Y (RTS_V4L2_CID_BASE + 23)
#define RTS_V4L2_CID_Y_GAIN (RTS_V4L2_CID_BASE + 24)
#define RTS_V4L2_CID_SMART_IR_MODE (RTS_V4L2_CID_BASE + 25)
#define RTS_V4L2_CID_SMART_IR_MANUAL_LEVEL (RTS_V4L2_CID_BASE + 26)
#define RTS_V4L2_CID_DAYNIGHT_DETECTION (RTS_V4L2_CID_BASE + 27)


#endif
